volumes:
  pg_data:


services:
  postgres:
    image: postgres:14 # debian slimベースのPostgres14の最新バージョン
    env_file: ../../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT:5432
