volumes:
  pg_data:


services:
  nestjs:
    build:
      context: ../../
      dockerfile: ./docker/production/Dockerfile
    ports:
      - ${NESTJS_PRODUCTION_PORT}:${NESTJS_PORT}
    restart: on-failure

  postgres:
    image: postgres:14 # debian slimベースのPostgres14の最新バージョン
    env_file: ../../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: on-failure
